### ISSUE TITLE
[Feature Request] Automatic updating of blocklist using txt?

### ISSUE THREAD

**Issue by TimoVerbrugghe** [WaLLy3K/wally3k.github.io#1]
Hi Wally3k,

Thanks for providing this blocklist on your website! I was wondering if it would be possible to create a txt version of the no-false-positives list (or just of the list without the ones that cross block multiple sites) so we could add all of these lists to pihole through adlists.list with automatic updating?

Thanks

**Comment by WaLLy3K** [comment]
Hey @TimoVerbrugghe, I've [had this suggested to me on Reddit](https://www.reddit.com/r/pihole/comments/6hq3u7/blocklist_question/dj11ai2/), and it's one I'm definitely considering how to best do, since there's a clear use case for automatic updating. (Despite the more cautious voice in me that says it should be probably done manually anyway :smile: )

I'm thinking of just scraping the HTML and ensuring that a text file is updated weekly from the results.

**Comment by TimoVerbrugghe** [comment]
Yeah, was thinking the same thing, some kind of scraper. Have limited coding knowledge though, so won't be able to help you, but take your time :).

Thanks for the quick response!

Timo Verbrugghe

On Thu, Jun 29, 2017, 04:47 WaLLy3K <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey @TimoVerbrugghe<https://github.com/timoverbrugghe>, I've had this suggested to me on Reddit<https://www.reddit.com/r/pihole/comments/6hq3u7/blocklist_question/dj11ai2/>, and it's one I'm definitely considering how to best do, since there's a clear use case for automatic updating. (Despite the more cautious voice in me that says it should be probably done manually anyway 😄 )

I'm thinking of just scraping the HTML and ensuring that a text file is updated weekly from the results.

**Comment by WaLLy3K** [comment]
I've looked into this a bit further - while I don't have the time right now to sort out things like categories and such, [here's something](https://github.com/WaLLy3K/wally3k.github.io/commit/3f879c3f1bd4d37430d287af1ac1eb2285d30307) that appears to suit your needs!
