### ISSUE TITLE
updated links (HOSTS)

### ISSUE THREAD

**Issue by eladkarako** [WaLLy3K/wally3k.github.io#13]
@WaLLy3K 
here is the updated link, for the <a href="http://hosts.eladkarako.com/">HOSTS repository</a>
<sub>used in <code>https://github.com/WaLLy3K/wally3k.github.io/blob/master/classification.ini</code></sub>.

<pre>
https://raw.githubusercontent.com/eladkarako/hosts/master/_raw__hosts.txt

<sub>also available...
HOSTS (HOSTS format)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_with_localhost.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts0_with_localhost.txt

HOSTS (HOSTS in <strong>AdBlock format</strong> for the browser)
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock.txt

AdBlock lists
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_block_inline_script.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_hide.txt
https://raw.githubusercontent.com/eladkarako/hosts/master/build/hosts_adblock_anti_annoyances_style_inject.txt
</sub>
</pre>

**Comment by WaLLy3K** [comment]
Hey @eladkarako,

I appreciate the input! For what it's worth, [classification.ini](https://github.com/WaLLy3K/wally3k.github.io/blob/master/classification.ini) is solely a supporting file for the now-superseded [Pi-hole Block Page](https://github.com/WaLLy3K/Pi-hole-Block-Page) which the repo has now been archived.

Since people should have updated their Pi-holes, there's no benefit in updating this file. :smile:
