### ISSUE TITLE
content.ibanking-services.com.

### ISSUE THREAD

**Issue by bakerboy448** [WaLLy3K/wally3k.github.io#147]
For lists https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt and https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt,  they have an entry for  #content.ibanking-services.com.

Blocking this entry requires banks who use FIS as their core provider, to always require 2FA everytime a  customer logs in.

Can these entries be reconsidered?  Yes technically its tracking, but it causes material impact to users and is not an easy one to track down.

**Comment by WaLLy3K** [comment]
I've sent a message off to the list maintainer via Twitter, linking back to this ticket. 🙂

**Comment by bakerboy448** [comment]
for posterity - still exists on https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt

**Comment by GeoffreyFrogeye** [comment]
Hi, sorry for not answering earlier, been procrastinating.

For the first-party list, it's been removed [since 2021-07-14](https://git.frogeye.fr/geoffrey/eulaurarien/commit/f5f9f88c4284bae7291ff9a5accbd7c6789e95ca).

The multi-party list is an automatically generated one, and is mostly designed for research or very cautious users. I cannot handle considering false-positives for this one. Honestly I think it should have the ✗ on https://firebog.net/ .
