### ISSUE TITLE
maybe parsing error

### ISSUE THREAD

**Issue by HaxXorHardy** [WaLLy3K/wally3k.github.io#163]
List: https://v.firebog.net/hosts/Easylist.txt

Number of invalid domains on this list:  1

Picture:
![firefox_tIPjazydSp](https://user-images.githubusercontent.com/1397712/188290634-365e8526-74f8-4450-b754-68ec9f0bca73.png)

**Comment by kotx** [comment]
The invalid entry is `wytyphoji.pro&popup`.

**Comment by rube200** [comment]
Original entry `wytyphoji.pro^&popup`

**Comment by SDeGonge** [comment]
FYI-same issue here.

**Comment by Ad-Blokker** [comment]
It seems like a parsing error because other entries with the **^&popup** from the original easylist are not being added to this list.
Link to original easylist:
https://easylist-downloads.adblockplus.org/easylist.txt


![image](https://user-images.githubusercontent.com/14195799/188757625-7af46e50-d266-4c3f-8c2a-41f81c5edbd8.png)

**Comment by SDeGonge** [comment]
Looks like the "&" should be a "$"... 
wysyshypti.pro^$popup
wytyphoji.pro^&popup
xaxoro.com^$popup

**Comment by Ad-Blokker** [comment]
> Looks like the "&" should be a "$"... 
> wysyshypti.pro^$popup
> wytyphoji.pro^&popup
> xaxoro.com^$popup

You are right, I am blind.
This seems like a problem with adblockplus?
