### ISSUE TITLE
All URL only text list are empty

### ISSUE THREAD

**Issue by seanob86** [WaLLy3K/wally3k.github.io#172]
https://v.firebog.net/hosts/lists.php

Open any of the lists e.g ‘Ticked Lists’, page opens blank with no URL’s. Should contain list of URLS. Same issue with ‘non crossed list’ or ‘All Lists’

![80A82A7D-FC2A-4112-8D9B-16CD0D7A3FF4](https://user-images.githubusercontent.com/45988261/202467663-6b100598-f584-4a94-a243-c4e5382a2fc2.png)

**Comment by panzer-arc** [comment]
I am seeing the same thing with this url:
https://v.firebog.net/hosts/lists.php?type=tick

**Comment by aclare92** [comment]
Second this, just checked and seen these are not working too so not just an issue for OP; they were working yesterday if that helps the maintainer

**Comment by WaLLy3K** [comment]
Thank you very much for the report! My lists.php script makes a copy of the HTML from the source and for some reason it stored a 0kb file.

I've manually wiped the blank file, and I'll implement a fix so it can't cache a blank file in the future when I can sit down and put some time into this later today.

I'll keep the ticket open until that issue is resolved!

**Comment by WaLLy3K** [comment]
Thanks @seanob86! I've added a filesize check into `lists.php` to ensure a blank cache file can't be created.
