### ISSUE TITLE
Please Update List! 

### ISSUE THREAD

**Issue by 103058167** [WaLLy3K/wally3k.github.io#175]
Hello, it is possible to update the list of websites on firebog.net manually? After looking at https://v.firebog.net/hosts/RPiList-Phishing.txt I can see that it hasn't been updated since 10FEB23. May I know how long do I have to wait before its updated again?

**Comment by WaLLy3K** [comment]
It should update every two days, however it looks like the update script was being auto-killed by the server it's running on due to trying to handle the absurd size of `Prigent-Adult.txt` within its limited available memory.

I've worked around this by removing `Prigent-Adult.txt` from the update list, but I'm going to have to find time to fix *that* issue.

Thanks for letting me know! 🙂
