### ISSUE TITLE
www.letemsvetemapplem.eu

### ISSUE THREAD

**Issue by michalachim** [WaLLy3K/wally3k.github.io#179]
hello, can someone please create a blacklist or regex for the website www.letemsvetemapplem.eu and supplement the current blacklists?  Current blacklists cannot block ads on this site.  Thank you

**Comment by WaLLy3K** [comment]
Background ad: https://www.letemsvetemapplem.eu/rekaaa/alzacache/363c2faa-45e5-45b6-954b-cb66d04385cc.jpg.webp

Ads throughout the page:
https://www.letemsvetemapplem.eu/amalker/2023/mp/04_1130_150_airpods_2990.jpg.webp
https://www.letemsvetemapplem.eu/amalker/2023/istorescz/02_Watch_2220x250.png.webp
https://www.letemsvetemapplem.eu/amalker/2023/mp/03_300_600_MBPM2.jpg.webp
https://www.letemsvetemapplem.eu/amalker/2023/istorescz/02_Mac_600x1200.png.webp
https://www.letemsvetemapplem.eu/amalker/2023/jbl/April_600x1200_CZ.png.webp
https://www.letemsvetemapplem.eu/amalker/2023/mp/04_300_600_airpods_2990.jpg.webp
https://www.letemsvetemapplem.eu/amalker/2023/psg/ocushield.png.webp
https://www.letemsvetemapplem.eu/amalker/2023/vocolinc/powerbanka.png.webp

DNS based adblocking cannot target unwanted content on the same domain as content you want to access. That's why browser based adblocking is complimentary, because it'd have no problem with nuking `https://www.letemsvetemapplem.eu/amalker/` from orbit once you've added a manual rule to target that! 🙂
