### ISSUE TITLE
ichnaea.netflix.com is blocked on adguard dns txt

### ISSUE THREAD

**Issue by madarie** [WaLLy3K/wally3k.github.io#182]
Please remove ichnaea.netflix.com from https://v.firebog.net/hosts/AdguardDNS.txt
This is needed to resume playing on netflix

**Comment by AJCxZ0** [comment]
None of the Netflix clients on my Roku, mobile or PC devices have any trouble resuming playback while `ichnaea.netflix.com` is not only blocked, but is the #2 most frequently blocked host on my Pi-hole.
This has been blocked with no adverse effect for years and absent strong evidence of a change in impact should remain blocked.

**Comment by WaLLy3K** [comment]
Hey @madarie, apologies for the delay in reply! I'd recommend opening an issue with @AdguardTeam at the  [AdGuardSDNSFilter repo](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues).

They're in a better position to judge whether it should be whitelisted due to false positive, and my copy will update with the fix within a couple of days.
