### ISSUE TITLE
LanikSJ/ubo-filters Admiral.txt is not in a pihole-parsable format

### ISSUE THREAD

**Issue by chrisbraucker** [WaLLy3K/wally3k.github.io#183]
Hi and thank you for your work, it is a pleasure having so many decent lists in one place.

To cut to the chase: I noticed that the adlist you cache on https://v.firebog.net/hosts/Admiral.txt is not in a format that pihole understands, and the author himself states that the adlists he supports are only maintained for Adblock / Plus / uBlock.
I'm considering running a GH action that reformats the list whenever the upstream changes, would this be of interest to you?

Best,
Chris

**Comment by WaLLy3K** [comment]
G'day @chrisbraucker,

Thanks for the praise! I already parse Adblock filter lists, but this one slipped by my parser because it checks the first line for `[[ "${list[head],,}" =~ (adblock|ublock|! checksum:) ]]` and treats the list accordingly. At some point, `getadmiral-domains.txt` (the upstream list) was changed so the first line read `! Title: GetAdmiral Domains Filter List` which isn't something I expected.

By checking simply for the presence of `! `, my parser will now treat an upstream list as an Adblock filter list and parse it accordingly.

I've updated Admiral.txt so that it is now parsed correctly, **so thank you for bringing this to my attention!** With that, I think that should also answer your question regarding the GitHub action. 🙂
