### ISSUE TITLE
vimeo.com blocked via ticked OSINT.digitalside.it list

### ISSUE THREAD

**Issue by AJCxZ0** [WaLLy3K/wally3k.github.io#186]
[vimeo.com](https://vimeo.com) is currently in the [OSINT.digitalside.it list](https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt)  which is one of the [ticked](https://v.firebog.net/hosts/lists.php?type=tick).

I just emailed [them](mailto:info@digitalside.it) _Remove vimeo.com from Threat-Intel/lists/latestdomains.txt_ requesting its removal.

**Comment by WaLLy3K** [comment]
No worries! Since that list is linked directly, the update will be available immediately to everyone — opposed to if it was a list I mirrored, which takes a few days after the upstream update for my mirror to update.

If you have any issues with getting that whitelisted, please let me know. I'll keep this ticket open so others coming across this can be mindful 🙂

**Comment by AJCxZ0** [comment]
Still present in [list](https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt) _Generated at: 2023-10-06 08:04:22_ 
No reply to email.

**Comment by WaLLy3K** [comment]
I completely missed your reply (absolutely unintentional!) and I notice this one is gone. Then again, it's a list that's supposed to be of the last seven days so I suspect things were sorted shortly after your reply here.

Did you end up getting a response to this, by any chance?

**Comment by AJCxZ0** [comment]
While I received no communication, it appears that [vimeo.com](https://vimeo.com) has been removed.

**Comment by WaLLy3K** [comment]
I'm a bit disappointed to hear the maintainer didn't reach out to you. That's something I'll keep in mind, because it's one of the reasons I rec a list.

Thanks for the quick reply despite my tardiness, I appreciate it 🙂
