### ISSUE TITLE
firebog.net is blocked on my country (Philippines) by Cloudflare?

### ISSUE THREAD

**Issue by Gyakusetsu** [WaLLy3K/wally3k.github.io#188]
It was working properly without this issue before
![image](https://github.com/WaLLy3K/wally3k.github.io/assets/51472970/283440c4-5c24-4c41-bfcb-33c527b2a1a9)

> curl https://v.firebog.net/hosts/static/w3kbl.txt
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to v.firebog.net:443

**Comment by WaLLy3K** [comment]
I suspect it'd be temporary routing issues to Cloudflare that I've seen happen with other countries over the years, that's typically resolved within a few days.

If there was another CDN with a free tier, I'd happily check them out, since the site doesn't generate the kind of income necessary to use a paid CDN.

**Comment by Gyakusetsu** [comment]
@WaLLy3K thank you for confirming I also used a temporary host from another country to verify, I'm closing this now.
