### ISSUE TITLE
Incorrect domain names

### ISSUE THREAD

**Issue by Wiggum127** [WaLLy3K/wally3k.github.io#191]
When parsing your list for a hosts file, I encountered 4 errors of incorrectly formatted domain names:

emam
smcom
smetriccom
smetrics.previcox.d

**Comment by Wiggum127** [comment]
Not very clear to me to which of your repo's this applies. 

But perhaps this can help. Initially reported the issue elsewhere:

https://github.com/easylist/easylist/issues/18218

And was informed to post the issue here.

**Comment by WaLLy3K** [comment]
Ah, I see! I'll look into this in the next few days and see why it's not stripping out invalid domains. 🙂

**Comment by WaLLy3K** [comment]
Oh shoot, I forgot to set a reminder to alert me since something else had came up. My bad!

**Comment by WaLLy3K** [comment]
Looking over my code, I don't actually perform *any* domain validation. For some reason, I thought I did. However, I've taken the time to clarify my stance in the [readme](https://github.com/WaLLy3K/wally3k.github.io?tab=readme-ov-file#on-the-subject-of-non-domain-entries) *(in that basically, I don't feel I should be making these kinds of changes and that Pi-hole does it already)*.

**Comment by Wiggum127** [comment]
Having read the statement in the readme, I gather the source of the domains is elsewhere.
Can you point me to the right direction to have it solved upstream, please?
Thanks.

**Comment by Wiggum127** [comment]
@WaLLy3K Can you point me to the right contact to it solved upstream, please ?

**Comment by AJCxZ0** [comment]
@Wiggum127 I'm not @WaLLy3K and don't play him in a popular Venezuelan telenovella, however since I've done this before and this case is closed, I'll try to help.

Nowhere in this case did you mention which of the many lists curated by @WaLLy3K contain these entries. If you're updating gravity on a Pi-hole, then you'll see which list contains these in the output, otherwise you'll need to find the list another way.
Once you have the URL for the list, view it it your browser. The lists often contain information in comments including contact details for the list owner.
What happens after you contact the list owner will of course depend on the list owner.
