### ISSUE TITLE
Airelle-trc blocks "www.howtogeek.com"

### ISSUE THREAD

**Issue by Dustee** [WaLLy3K/wally3k.github.io#27]
Hi, i hope this is the right place to report false positives. 
I can't find a reason why howtogeek should be blocked.

Also i would like to ask if there is an optimal way to figure out which list is responsible for a block, because my lists in /etc/pihole are using different names compared to the https://wally3k.github.io/ page.

**Comment by WaLLy3K** [comment]
Hey @Dustee 

You're right, I don't think it's appropriate that HowToGeek should be blocked. I've let Airelle know, and have removed those lists from the tick recommendation.

If you're looking to find which list is causing a site to be blocked, hit up the Command Line Interface and use `pihole -q -adlist blocked.com` - it'll return the URL of the list it was found in, instead of the `*.domains` internal file name.

Thanks!
