### ISSUE TITLE
Text-only version of adlist broken

### ISSUE THREAD

**Issue by bobsoppe** [WaLLy3K/wally3k.github.io#33]
In the past https://v.firebog.net/hosts/lists.php?type=tick showed a nice text-only list of all adlists in "The Big Blocklist Collection". But now it shows a non styled version of https://wally3k.github.io.

**Comment by W0CHP** [comment]
Can reproduce here as well.

**Comment by WaLLy3K** [comment]
The PHP file that parses this apparently got replaced with a text-only version of the Big Blocklist. I'm honestly not sure how I caused that to happen (it almost certainly wasn't done by the script itself!), but it's resolved now since @Promofaux brought it to my attention.

I'm pretty embarrassed, but thank you for the heads up!
