### ISSUE TITLE
AdguardDNS - googleadapis.l.google.com

### ISSUE THREAD

**Issue by HellboyPI** [WaLLy3K/wally3k.github.io#4]
Hello!
The domain googleadapis.l.google.com is in the AdguardDNS exceptions, because it blocks fonts.googleapis.com. The exceptions are at the end of the [official list](https://filters.adtidy.org/extension/chromium/filters/15.txt). Click [here ](https://github.com/AdguardTeam/AdguardDNS/issues/63)for more info. But in the AdguardDNS firebog list googleadapis is still there.

**Comment by WaLLy3K** [comment]
That's a great observation, and not one I've made myself!

My adblock parsing works by looking at any domain that has `||` and `^` in a single line, in this case, `||googleadapis.l.google.com^`, and doesn't consider any of the exceptions.

I'll have to look into the code and figure out how I can best fix this issue.

**Comment by WaLLy3K** [comment]
My adblock parser now takes `@@||domain.com^` styled exceptions into account. `AdguardDNS.txt` has been regenerated manually, and Cloudflare's cache of this list has been refreshed.

If there's any other adblock lists that are affected by this issue, they will be updated the Sunday (US time) after the source content is updated (since I only check for updates weekly).

If you or anyone else spot any other issues with my lists, *please* let me know - my adblock parser is my own work, and there's probably more little nuances like this that I've missed! :smile:

Thanks again for the report @HellboyPI!
