### ISSUE TITLE
Question icanhazip.com blocked 

### ISSUE THREAD

**Issue by POTATOES-BoilEm-MashEm-StickEm-inAStew** [WaLLy3K/wally3k.github.io#43]
Not sure if I'm posting this in the correct github repo (instead of list hosters/creators)[please do not get angry if im wrong to post it here].

These blocklists block the domain icanhazip.com:

https://v.firebog.net/hosts/Airelle-hrsk.txt [included in firebog.net]
https://tspprs.com/dl/malware
https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Malware-HOSTS-FilterList.txt

Why do these lists block icanhazip.com? 

Is it because some malware gets and determines the IP using this domain?
Is it not a false-positive since it can be used for good: to determine IP in a script. The domain itself is harmless.

**Comment by kyle95wm** [comment]
This is also mildly infuriating. This is why local whitelists exist, but I honestly hate that useful websites like these are blocked. ifconfig.me is a good alternative.

**Comment by WaLLy3K** [comment]
Hey @POTATOES-BoilEm-MashEm-StickEm-inAStew,

I'd definitely have a laugh at the name well before ever getting mad for asking a question :)

If I may make a semi-educated guess as to why that domain is blocked:

* Airelle has probably included it by mistake. I'm not sure how Airelle vets his(?) lists, but I've had to demote those maintained by him due to the ongoing frequency of false positives
* Tspprs is simply a consolidated mirror of all the content found here (which is *not* a practice I approve of, but I digress), plus probably from a few other sources and so has probably inherited this match from Airelle
* I'm not sure why CHEF-KOCH would block it, but it could possibly be due to the above reason

Oddly, I've also seen `ipify.org` blocked by various lists; maybe it's because as you say, they've been used by malware to determine an IP address... but it definitely sounds like a ham-fisted solution to block IP checking providers like this.

Honestly, it's hard to find *original* sources for HOSTS. Most of what you see online is essentially regurgitated content with someone else's name slapped on it, which is why I endeavour to link to the source whenever possible.

If you're looking to get an IP via a `bash` script, I wholeheartedly recommend the following snippet:
```
timeout 0.5 dig +short myip.opendns.com @resolver1.opendns.com 2> /dev/null
```

**Comment by WaLLy3K** [comment]
Hopefully this question has been answered satisfactorily!
