### ISSUE TITLE
Add big merged lists like EnergizedProtection ?

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#46]
What did you think? It is better to list big lists like https://github.com/EnergizedProtection/block instead of the sources ?
A big list would reduze work for users and traffic, but need trust that the dev do the work / their automatic script works

**Comment by WaLLy3K** [comment]
Hey @beerisgood,

I think the cons outweigh the pros, but let's break the ones I can think of (off the top of my head) down for argument sake:

**Pros**
* Easier to install: one line to copy and paste makes things real simple to get a lot of blocked content
* Gravity executes quicker: only having to make one connection means the weekly script is done faster

**Cons**
* Technical single point of failure: if the list is unavailable (server outage) or if the list maintainer's update mechanism fails, you're left with a stale blocklist
* Moral single point of failure: you may not have any recourse if a "bad" site is whitelisted (e.g: maintainer gets a kickback from a tracking company), or a "good" site is blacklisted
* Slower updates: some lists update daily, others update weekly and others monthly. The lists that update daily are typically malicious, such as phishing
* Waste of bandwidth: if a single line changes, the whole list needs to be re-downloaded. Also if hosted on GitHub, will lack the `last-modified` header, which will cause the list to redownload *every* time gravity is run
* Original content gets less visibility: most hosts blocklists are mirrors of other people's hard work. If those *original* list maintainers get less and less hits due to these consolidated lists becoming the de-facto go-to, they may have less incentive to keep their content up to date and could stop working entirely on it

Personally, I believe in de-centralisation whenever practical and so relying on a single person for my blocklist content doesn't sit well with me.
