### ISSUE TITLE
Bad Lists

### ISSUE THREAD

**Issue by kyle95wm** [WaLLy3K/wally3k.github.io#49]
The following lists have 404 errors:

https://raw.githubusercontent.com/CHEF-KOCH/BarbBlock-filter-list/master/HOSTS.txt

https://raw.githubusercontent.com/CHEF-KOCH/CKs-FilterList/master/HOSTS/CK's-Spotify-HOSTS-FilterList.txt

https://raw.githubusercontent.com/CHEF-KOCH/Canvas-Font-Fingerprinting-pages/master/Canvas.txt

https://raw.githubusercontent.com/CHEF-KOCH/Canvas-fingerprinting-pages/master/Canvas.txt

https://raw.githubusercontent.com/CHEF-KOCH/WebRTC-tracking/master/WebRTC.txt

https://raw.githubusercontent.com/CHEF-KOCH/Audio-fingerprint-pages/master/AudioFp.txt

**Comment by POTATOES-BoilEm-MashEm-StickEm-inAStew** [comment]
The github account of Chef Koch has been deleted by github. No idea where his new lists will be placed for now

> Hello, my GitHub Account got suspended (for 8. time) this normally happens when the GitHub Bot scans and detects something which is on their blacklist.
GitHub does not warn you or gives you the opportunity to react, it simply shutdowns you account automatically, you also won't get any eMail in order to get informed.
The User LainUnchained informed me via Discord that there is currently a problem (thanks), in the meanwhile, I already contacted GitHub in order to (yet again) resolve this, so everything will be visible again in the next two days.
Also please do not open any issue ticket here since I and gorhill have a personal conflict due to his actions in the past and I not like to see my name on his projects or here because I normally not check Reddit nor this sub-category.
Thanks for respecting my wish and sorry for the inconvenience. - Chef Koch

see 

https://www.reddit.com/r/uBlockOrigin/comments/9opkel/chefkoch/e7x35q5/

Old hard  copy of his lists here: https://github.com/TorstenJahnke/CHEF-KOCH but those will probably not be updated. Guess we'll have to wait and see if and where he will drop the lists.

**Comment by dietavor** [comment]
I think (and hope) that he will never come back. His account was deleted due to the fact that one of his gists contained links to explicit content involving minors. The only thing CHEF-KOCH ever did was plagiarizing other people´s work as many issues on github prove. Seems like he copied one too much...

If you are interested:
https://github.com/ghacksuserjs/ghacks-user.js/issues/323

Can´t find the other sources right now but he did the same with stuff from gorhill (uBlock Origin), maloe/Mike Kuketz (ASN blocking script), ...

**Comment by WaLLy3K** [comment]
I've removed the links for now. Thanks for opening an issue and letting me know :)

**Comment by kyle95wm** [comment]
Thanks for the update! It seems your "parsing" domains (the ones that have just the URLs in plain-text) haven't updated yet. Is this normal?

**Comment by WaLLy3K** [comment]
Ah, right! That gets checks for updates every 24 hours, so it will have sorted itself out by now :smile:
