### ISSUE TITLE
CHEF-KOCH lists again online

### ISSUE THREAD

**Issue by vedriritam** [WaLLy3K/wally3k.github.io#54]
Hi, chef-koch lists are back online could you re-add them?

**Comment by beerisgood** [comment]
Why? He only steal work from others, without any sources

**Comment by ail1020** [comment]
agreed, I'm fine with not including chef's lists in the future. Because of his list removal I learned about all his shady copy projects where he'd remove the original author's information from the project and take credit himself. I didn't notice any drop in blocked domain count when I removed his lists, so that tells me I've got the lists he stole from covered.

**Comment by anothernewusername** [comment]
+1 for not using his lists. I did know about his copy-paste-skills from stealing the idea of a block script based on ASN from maloe and Mike Kuketz (can now be found on notabug). Furthermore just like ail1020 there was absolutely no difference in the amount of blocked domains after removing CK´s lists. All of the original sources seem to be included in the lists you provide anyway.

**Comment by WaLLy3K** [comment]
Thanks for the heads up @vedriritam, though I think I'll be not adding his lists this time unless they add something particularly valuable, with minimal false positives. Cheers :)
