### ISSUE TITLE
dbl.oisd.nl

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#65]
Today i found that (realy big) list:
https://www.reddit.com/r/pihole/comments/bppug1/introducing_the/?sort=new
-> https://dbl.oisd.nl/

Maybe add it to your's?

**Comment by dmginc** [comment]
That list has a ton of false positives, despite the grand write up the creator made.

**Comment by beerisgood** [comment]
Any examples?

**Comment by dmginc** [comment]
Malwarebytes update domains. Most amp sites. Several random charity sites. 

It's a good list, but definitely not close to ready yet.

**Comment by beerisgood** [comment]
Well, blocking AMP sites is good.
But thanks for your input. I will test it and see then

**Comment by dmginc** [comment]
Not really, since they're still returned in search results.  Lots of questions from end-users/family about why the "internet isn't working".

**Comment by beerisgood** [comment]
To be fair i never see any AMP sites nor have family users which see them.

**Comment by ZeroDot1** [comment]
@beerisgood @dmginc I have no problem with the list since I maintain a very large white list.

**Comment by sjhgvr** [comment]
The only list I use is dbl.oisd.nl, no issues 👍

**Comment by beerisgood** [comment]
So I guess it's safe to use then.
And if any false positives exist, like dmginc say, I be sure the devs fix it after telling them.

@WaLLy3K: what did you mean?

**Comment by sjhgvr** [comment]
True. Just let me know if you find any false positives and I will fix them :)

**Comment by lightswitch05** [comment]
> The only list I use is dbl.oisd.nl, no issues 👍

This is a bit of a problem, because this is a list-of-lists. Which in itself isn't terrible (see Steven Black's list) - but problems with the list do not get reported upstream. 

For example, my list is included in this list-of-list, however, if someone complains to @sjhgvr that a domain is breaking some functionality - then he whitelists it directly in his list and the report never find it back to me. I consider this a major problem. As the list maintainer, I work hard to provide a reasonable and reliable- but when I never receive feedback when people have issues - then there is no way for me to improve my list.

If anyone is interested, my lists can be found here: https://github.com/lightswitch05/hosts 

The one being used by @sjhgvr is my primary 'Ads & Tracking' list here: https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt

I would be honored to have my list in this project, but I would not want it included indirectly through  another list without receiving feedback.

**Comment by sjhgvr** [comment]
@lightswitch05 
My current blocklist does NOT include your list.

**Comment by lightswitch05** [comment]
That must be a somewhat recent change. Thanks for the update @sjhgvr

**Comment by WaLLy3K** [comment]
> This is a bit of a problem, because this is a list-of-lists. Which in itself isn't terrible (see Steven Black's list) - but problems with the list do not get reported upstream.

> if someone complains to <any curated blocklist maintainer> that a domain is breaking some functionality - then he whitelists it directly in his list and the report never gets back to <original blocklist source>. I consider this a major problem. As the list maintainer, I work hard to provide a reasonable and reliable list- but if I never receive feedback when people have issues - then there is no way for me to improve my list.

This is precisely my line of thinking. @lightswitch05, would you mind letting me know how you source the content in your blocklist? I am always keen to add new content, but just don't have the time these days to find and vet stuff in-depth like I used to.

**Comment by lightswitch05** [comment]
> would you mind letting me know how you source the content in your blocklist?

I use uBlock origin while browsing on my computer and check what domains are being used. For mobile, I regularly check my pi-hole audit log to see if anything looks fishy. I have a python script that attempts to find subdomains for any root domain I’ve blocked - like `googleanalytics.com` would expand out to `ssl.googleanalytics.com`. To find subdomains, it uses a combination of certificate transparency logs and VirusTotal.
