### ISSUE TITLE
Frogeye tracking list

### ISSUE THREAD

**Issue by frankrpi3** [WaLLy3K/wally3k.github.io#73]
Hi,

when adding the new frogeye tracking list, sites like tumblr, pinterest and others are completely blocked. I don‘t know if you agree, but this list should not be marked as „ticked“!

btw I thought that you retired from this great project as there were no activities in the last months. Glad to see you active again!

Regards, Frank

**Comment by WaLLy3K** [comment]
> when adding the new frogeye tracking list, sites like tumblr, pinterest and others are completely blocked. I don‘t know if you agree, but this list should not be marked as „ticked“!

That's definitely frustrating. I've let the developer know via Twitter (as I don't know how active they are via GitHub), but there's clearly a bit of a flaw with how the list is generated and thus isn't suitable for the tick list.

The idea behind the tick is to have as minimal false positives as possible, preferably causing no extra maintenance for unmaintained Pi-hole instances.

> btw I thought that you retired from this great project as there were no activities in the last months. Glad to see you active again!

Real world duties combined with the fact I never get push notifications on my phone made it really difficult to remember to keep on top of things. CodeHub on iOS is currently providing me notifications of ticket updates, so that means it's easier to find 5 minutes to provide input on issues. 🙂

**Comment by GeoffreyFrogeye** [comment]
> I've let the developer know via Twitter (as I don't know how active they are via GitHub)

You can contact me on GitHub any time as long as you mention me :)

> here's clearly a bit of a flaw with how the list is generated and thus isn't suitable for the tick list

I think you're right. The way the list is generated is that it's trying to find every domain trying to hide a tracking domain by putting it behind a DNS redirection. Since a lot of existing trackers seems to be adopting this new technique, I'm basically using existing lists to match those.

All the source lists I'm using are ticked on this website, however while that might be relevant when blocking the visible domain, it doesn't have to be when blocking all the redirection layers.
For example, `chicdn.net` is blocked in the `notrack-blocklist`, probably because it serves tracking scripts as a third party, but `api.tumblr.com` resolves to `cs1143.wpc.chicdn.net` which my list would block...

I've removed the not-suited-for-first-party lists from my source which makes tumblr and pinterest browsable again, but that's not a guarantee that there won't be false positives anymore.

I'm considering not using existing lists as a source and manually adding trackers known as first-party, but that won't be as efficient. On the other hand there should not be any false positive.

**Comment by WaLLy3K** [comment]
> that's not a guarantee that there won't be false positives anymore

At the very least, the aim of my lists aren't to *not* have false positives (just because that isn't a reasonable expectation to have when one is blocking excess of tens of thousands of domains), but to have maintainers resolve the false positives as quickly as possible, and have as few FP's as possible for those end users who aren't in a position to frequently whitelist sites when issues crop up.

I'm hoping I will find the time to really vet the lists thoroughly (and get good feedback from those who use the tick+nocross lists like I do), so it doesn't have a "trial by fire" (so to speak) like @frankrpi3 has experienced, therefore letting me put it back in the tick lists where I feel this list should belong.

Your writeup is very informative, and *I definitely* appreciate the prompt reply! Thank you for taking the time to tackle the issue of first party tracking. 😄

**Comment by GeoffreyFrogeye** [comment]
So I've made [the current list](https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt) only block domains that I'm sure are first-party trackers ([all 6 of them](https://git.frogeye.fr/geoffrey/eulaurarien/src/branch/master/rules/first-party.list) :smile:). It decrease tenfold the number of blocked domains but there should be way less false positives (unless those trackers also starts serving legitimate content, which... could be a strategy to get them removed from the list). IMHO it is now suitable for the tick.

I've kept the old list at <https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt>. I'll be using it to find "real" first-party trackers and add it them the first list. I'd rather add trackers one by one than remove false positives one by one. This list as is might still be useful for some users, so feel free to add it to your list if you want, albeit maybe with a cross :)

**Comment by WaLLy3K** [comment]
So to confirm, the existing URL I have (https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt) has now been updated to only serve confirmed first party trackers, while the new URL (https://hostfiles.frogeye.fr/multiparty-trackers-hosts.txt) has been updated with the content that was found in the first URL. Is that correct? 🙂

**Comment by GeoffreyFrogeye** [comment]
It is correct :)

**Comment by WaLLy3K** [comment]
Legend, thank you!

I'm now comfortable with marking this issue as resolved. If there's any further issues with this list, anyone is absolutely welcome to open a new issue! 😊
