### ISSUE TITLE
Change Spam404 links

### ISSUE THREAD

**Issue by XhmikosR** [WaLLy3K/wally3k.github.io#92]
* https://github.com/Spam404/lists
* https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt

I was also wondering, any reason for not including this list to the ticked ones?

**Comment by WaLLy3K** [comment]
Ah, these are @Dawsey21's lists under a new name. No worries, I can update that.

The reason they weren't ticked is because *anything* I put under the suspicious category (which I use as a nicer word than 'generic') is considered too broad to warrant being ticked.

Based off my read-through of the list, this appears to be targeted more towards phishing (e.g: `steamcommnnity.com` or `gtavmoneycheat.com`) so I'm happy to tick this under the Malicious category.

Thanks for raising the issue @XhmikosR! :)
