### ISSUE TITLE
False positive - BillStearns.txt - windows.net

### ISSUE THREAD

**Issue by zappeee** [WaLLy3K/wally3k.github.io#93]
windows.net is blocked by BillStearns.txt.
Mistake or should there be a cross in front of this list also?

**Comment by WaLLy3K** [comment]
I'd say once upon a time when this list was still being updated, `windows.net` wasn't owned by Microsoft.

Due to its age, this list is one of the few exceptions where I'm happy to modify the copy I'm hosting, so I've removed that domain as well as the few IP addresses that were sitting in that list. Cloudflare cache has been purged for this file, so changes are effective immediately.
