### ISSUE TITLE
replace https://v.firebog.net/hosts/AdguardDNS.txt with original

### ISSUE THREAD

**Issue by beerisgood** [WaLLy3K/wally3k.github.io#94]
The original AdGuard DNS based filterlist is: https://filters.adtidy.org/extension/chromium/filters/15.txt

Source: https://kb.adguard.com/en/general/how-malware-protection-works

**Comment by WaLLy3K** [comment]
I already use [the exact list you linked](https://filters.adtidy.org/extension/chromium/filters/15.txt) as the source for [my filtered list](https://v.firebog.net/hosts/AdguardDNS.txt) which gets automatically updated once a week, which is less often than what the original list gets updated. The original list is in an Adblock format, which Pi-hole won't accept.

**Comment by beerisgood** [comment]
Okay. Thanks for the info.
Maybe but that in your list so other users know that

**Comment by WaLLy3K** [comment]
I'm not comfortable setting my update script to run every day, but I can compromise with every three days.

The reason is that my script has a few safeguards in place to prevent a webmaster seeing it as abuse - it will ignore any file that's been updated in the last 24 hours, and will first query the `Last-Modified` HTTP header to see if the file has been changed remotely before pulling it down. If there's no LM header (as is the case with ALL files hosted on `githubusercontent.com`), it pulls the file down and compares them.

Three days should be a fair compromise, because I typically don't have any avenue for appeal if my server's IP address gets blocked by a webmaster.
