### ISSUE TITLE
Move Lightswitch05's ads-and-tracking-extended.txt to non-crossed lists?

### ISSUE THREAD

**Issue by Obihoernchen** [WaLLy3K/wally3k.github.io#99]
I think the [Lightswitch05's ads-and-tracking-extended.txt](https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
) list should be moved from ticked list to non-crossed lists.

This list blocks stuff like Xbox Live Achievements (see: https://github.com/lightswitch05/hosts/issues/161) and definitely needs some whitelisting for other sites as well. You can read about his opinion here: https://github.com/lightswitch05/hosts/issues/161#issuecomment-615924919
I'm not saying this is bad but in my opinion this shouldn't be on the ticked list as it requires manual intervention.

What do you think?

**Comment by WaLLy3K** [comment]
You definitely make a valid argument here and I’ll happily demote this list as soon as I get a chance in the next couple of days :)

**Comment by llacb47** [comment]
I disagree, not everyone in the world is an xbox user. The domains that break achievements are in several other hosts files and are easily found at the pihole forum's "Commonly Whitelisted Domains" page (https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212). The maintainer is very responsive to all feedback and whitelist requests.

`definitely needs some whitelisting for other sites as well`
If you have a suggestion for a whitelist please file an issue: https://github.com/lightswitch05/hosts/issues/new

**Comment by lightswitch05** [comment]
Oh hey. It’s an analytics server. My list is tracking-blocking list, which includes analytics. They use analytics to generate the achievements. Without analytics, they don’t generate anything. Feel free to remove the list if you don’t think it’s a good fit.

**Comment by WaLLy3K** [comment]
The point of the tick lists is for a “hands off” next to no manual intervention required Pi-hole experience (e.g: Work, your grandparents place, or someone with otherwise very minimal time to spare fixing broken things).

If people are happy to troubleshoot the occasional mis-blocked thing, then this is exactly what the non ticked lists are for. 🙂

**Comment by lightswitch05** [comment]
> definitely needs some whitelisting for other sites as well

I encourage tickets in my repo, so feel free to let me know what else you think needs whitelisting and we can have a discussion about it.

**Comment by Obihoernchen** [comment]
I'm not talking about removing anything. I'm just talking about **maybe** moving it to another category.

There are 3 categories https://v.firebog.net/hosts/lists.php:

> Available List Types (all exclude Pornography) and use cases:
> - Ticked lists: For when installing Pi-hole where no one will be whitelisting falsely blocked sites
> - Non-crossed lists: For when someone is usually around to whitelist falsely blocked sites
> - All lists: For those who will always be around to whitelist falsely blocked sites

I know you are super responsive etc. that's totally fine and your list is great! I even use it myself ;)

But I think it maybe should belong to the "_For when someone is usually around to whitelist falsely blocked sites_" category, instead of the "_For when installing Pi-hole where no one will be whitelisting falsely blocked sites_" category.
According to your comment: "_So my general rule of thumb is to block it all and let people whitelist whatever they decide is trustworthy. I prefer opt-in._" you target the "_For when someone is usually around to whitelist falsely blocked sites_" audience I guess?

PS: I didn't open issues because it's mostly sites/devices that need some tracking URLs whitelisted to work properly. This should be opt-in according to your rule of thumb anyways and I'm totally fine with whitelisting those, but I'm also not a "hands off" user.

**Comment by lightswitch05** [comment]
1. I’m glad you like the list
2. This is wally3k’s project and I respect whatever decision he makes. I haven’t said one way or the other what my opinion is on this ticket
3. The domain in question is 100% tracking and analytics. It’s not a false positive. Yes, opt-in is my rule of thumb when legitimate services break due to a legitimate block.
4. My list is a tracking list and it’s currently in the tracking category on this project
5. I’ve gotten whitelist requests before because the person was unable to watch advertisements... it’s impossible to make everyone happy.

Anyways please come open tickets in my project if you have any whitelisting requests.

**Comment by beerisgood** [comment]
@llacb47 
> I disagree, not everyone in the world is an xbox user.

Then their is no reason to block it ;)

**Comment by WaLLy3K** [comment]
@Obihoernchen brings up the most important point for how a list should be categorized, which is the mindset I come into this and any other tick related suggestion with:

> Ticked lists: For when installing Pi-hole where no one will be whitelisting falsely blocked sites 
> Non-crossed lists: For when someone is usually around to whitelist falsely blocked sites

In this case, just ignore the phrasing of "false positive" or "falsely blocked" since I really should be saying something like "No one will be around to create whitelist exceptions on blocked domains" just to be more neutral and avoid implying blame.

As @lightswitch05 has mentioned, you can't make everyone happy. Though with v5 out today, it's definitely a lot easier to whitelist domains on a per-client basis!

-----

It would be good to confirm whether it's just this that needs to be whitelisted:
> v10.events.data.microsoft.com
> v20.events.data.microsoft.com

Or if it's also:
> watson.telemetry.microsoft.com
> web.vortex.data.microsoft.com

Not being an Xbox user myself, I can't personally test this.

Given that the first two domains [have a very long-standing mention here](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212) which I already link to on the front page, I'm thinking we could keep the list where it is on the ticklist because I do reasonably expect one to finish setting up a Pi-hole *after* checking any existing known linked-to whitelist exceptions and then just letting the sinkhole do its magic without any further intervention.

**Comment by frankrpi3** [comment]
I also suggest to put it on the non-ticked list.

As pi-hole 5.0 is up and integrates CName blocking, for example google fonts are not displayed correctly on websites anymore using this blocklist.

fonts.gstatic.com (blocked gstaticadssl.l.google.com)

Also some redirections are blocked now, which I have to whitelist now:
1.ftb.al (blocked custom.bnc.lt)
vg01.met.vgwort.de (blocked slb-vgwort-de-pool02.vgwort-de.2cnt.net)
...

**Comment by lightswitch05** [comment]
Yes CNAME blocking is something I’m not sure how to handle yet. I didn’t realize it was on by default until recently. That’s good point. Anyone can make a CNAME dns entry to anywhere- so it basically impossible to verify your not breaking something somewhere. Please uncheck my list.

**Comment by lightswitch05** [comment]
As for google fonts:

```
Exact matches for gstaticadssl.l.google.com found in:
  - https://v.firebog.net/hosts/static/w3kbl.txt 
```

But I also have no intention to remove it from my list.

**Comment by WaLLy3K** [comment]
> As for google fonts:
> 
> ```
> Exact matches for gstaticadssl.l.google.com found in:
>   - https://v.firebog.net/hosts/static/w3kbl.txt 
> ```

Ooh thanks for pointing this out, I've removed that from my list. I've come to believe that this definitely shouldn't be blocked on a tick list because while I have no doubt that Google are tracking the web with embedded fonts similar to the Facebook "like" button, you can't always go without fonts depending on how poorly a web developer has designed their site.

> But I also have no intention to remove it from my list. Related ticket: [lightswitch05/hosts#136](https://github.com/lightswitch05/hosts/issues/136)

I think it's fair that people are confronted with the decision to whitelist it or leave it blocked, but only when they consent to the dramatically increased likelihood of false positives via their choice in blocklists.

Thanks @lightswitch05, I really appreciate your input 😄
